<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Commune;
use App\Models\Parish;

class CommunesTableSeeder extends Seeder
{
    public function run()
    {
        // Comunas agrupadas por parroquia (ejemplo simplificado)
        $communesByParish = [
    // Amazonas
    'Capital Alto Orinoco' => ['Comuna Integral Alto Orinoco', 'Comuna Renacer de la Selva', 'Comuna Productiva Orinoco I'],
    'Huachamacare' => ['Comuna Serranía de Huachamacare', 'Comuna Autóctona del Cerro'],
    'Marawaka' => ['Comuna Ancestral Marawaka', 'Comuna Tierra de Tepuyes'],
    'Mavaca' => ['Comuna Orillas del Mavaca', 'Comuna Corazón de la Amazonía'],
    'Sierra Parima' => ['Comuna Fronteriza Parima', 'Comuna Guardianes del Pulmón Verde', 'Comuna Parima B'],
    'Capital Atabapo' => ['Comuna Confluencia del Atabapo', 'Comuna Sol del Ventuari'],
    'Ucata' => ['Comuna Ucata Unida', 'Comuna Ribereña'],
    'Yapacana' => ['Comuna Parque Nacional Yapacana', 'Comuna Mineralógica del Sur'],
    'Caname' => ['Comuna Caname Productiva', 'Comuna Manare del Este'],
    'Fernando Girón Tovar' => ['Comuna Héroes de Atures', 'Comuna Central Fernando Girón', 'Comuna Samán de Atures'],
    'Luis Alberto Gómez' => ['Comuna El progreso de Gómez', 'Comuna La Esperanza del Sur'],
    'Pahueña' => ['Comuna Mirador del Orinoco', 'Comuna La Esmeralda de Pahueña'],
    'Platanillal' => ['Comuna Corazón de Platanillal', 'Comuna Vencedores del Llano Amazónico'],
    'Samariapo' => ['Comuna Puerto de Samariapo', 'Comuna Puerta del Amazonas'],
    'Sipapo' => ['Comuna Corazón del Sipapo', 'Comuna Autana Mágica'],
    'Munduapo' => ['Comuna Pescadores de Munduapo', 'Comuna Orilla del Orinoco'],
    'Guayapo' => ['Comuna Guayapo Renace', 'Comuna Tierra Fértil'],
    'Capital Manapiare' => ['Comuna Manapiare Unida', 'Comuna Serranía Viva'],
    'Alto Ventuari' => ['Comuna Nacientes del Ventuari', 'Comuna Cacique Yapacana'],
    'Medio Ventuari' => ['Comuna Etnia Yekuana', 'Comuna Corazón de la Selva'],
    'Bajo Ventuari' => ['Comuna Orillas del Ventuari', 'Comuna Sol de Manapiare'],
    'Capital Maroa' => ['Comuna Frontera de Maroa', 'Comuna Guainía Productiva'],
    'Victorino' => ['Comuna Victorino Resiliente', 'Comuna Brazo Casiquiare'],
    'Capital Río Negro' => ['Comuna San Carlos de Río Negro', 'Comuna Triple Frontera'],
    'Casiquiare' => ['Comuna Brazo Casiquiare', 'Comuna Aguas Negras'],
    'Cocuy' => ['Comuna Piedra del Cocuy', 'Comuna Guardianes del Sur'],
    'San Carlos de Río Negro' => ['Comuna Ecosocialista San Carlos', 'Comuna Río Negro Vive'],

    // Anzoátegui
    'Capital Anaco' => ['Comuna Gasífera de Anaco', 'Comuna Corazón de Anaco', 'Comuna El Progreso Anaquense'],
    'San Joaquín' => ['Comuna Vencedores de San Joaquín', 'Comuna El Esfuerzo Campesino'],
    'Buena Vista' => ['Comuna Mirador de Buena Vista', 'Comuna Tierra de Gracia'],
    'Capital Aragua de Barcelona' => ['Comuna Histórica de Aragua', 'Comuna Sol de Oriente'],
    'Cachipo' => ['Comuna Productiva de Cachipo', 'Comuna Llano Adentro'],
    'Bergantín' => ['Comuna Turística de Bergantín', 'Comuna Río Neverí'],
    'Caigua' => ['Comuna Indígena de Caigua', 'Comuna Teresén de Caigua'],
    'El Carmen' => ['Comuna Central El Carmen', 'Comuna Barcelona Heroica'],
    'El Pilar' => ['Comuna El Pilar en Lucha', 'Comuna Vía Alterna'],
    'Naricual' => ['Comuna Carbonífera de Naricual', 'Comuna Montaña Adentro'],
    'San Cristóbal' => ['Comuna San Cristóbal de Cumanagotos', 'Comuna Costanera del Neverí'],
    'Capital Bruzual' => ['Comuna Clarines en Batalla', 'Comuna Viento de Bruzual'],
    'Guanape' => ['Comuna Valles de Guanape', 'Comuna Tierra de Cacao'],
    'Sabana de Uchire' => ['Comuna Laguna de Uchire', 'Comuna Puerta de Oriente'],
    'Capital Cajigal' => ['Comuna Onoframe en Lucha', 'Comuna Corazón de Cajigal'],
    'San Pablo' => ['Comuna Agrícola de San Pablo', 'Comuna El Renacer del Campo'],
    'Capital Carvajal' => ['Comuna Valle de Guanape Unida', 'Comuna Productores de Carvajal'],
    'Santa Bárbara' => ['Comuna Ganadera de Santa Bárbara', 'Comuna Sol de los Llanos Orientales'],
    'Lechería' => ['Comuna Turística El Morro', 'Comuna Mar de Lechería'],
    'El Morro' => ['Comuna Cerro El Morro', 'Comuna Pescadores de Lechería'],
    'Capital Freites' => ['Comuna Cantaura en Victoria', 'Comuna Mesa de Guanipa'],
    'Santa Rosa' => ['Comuna Santa Rosa de Ocopi', 'Comuna El Esfuerzo de Todos'],
    'Urica' => ['Comuna Batalla de Urica', 'Comuna Renacer de Freites'],
    'Libertador' => ['Comuna El Libertador del Sur', 'Comuna Freites Avanza'],
    'Huanipa' => ['Comuna Indígena Kariña de Huanipa', 'Comuna Legado Ancestral'],
    'Capital Guanipa' => ['Comuna San José de Guanipa', 'Comuna El Tigrito Productivo'],
    'Capital Guanta' => ['Comuna Portuaria de Guanta', 'Comuna Mar y Montaña'],
    'Chorrerón' => ['Comuna Altos de Chorrerón', 'Comuna La Sirena de Guanta'],
    'Capital Independencia' => ['Comuna Soledad Heroica', 'Comuna Orillas del Orinoco'],
    'Mamo' => ['Comuna Productores de Mamo', 'Comuna Independencia Sur'],
    'Capital Libertad' => ['Comuna San Mateo de Libertad', 'Comuna Corazón de Anzoátegui'],
    'San Mateo' => ['Comuna Histórica de San Mateo', 'Comuna El Viñedo'],
    'Capital McGregor' => ['Comuna El Chaparro Avanza', 'Comuna Sol de McGregor'],
    'El Chaparro' => ['Comuna Renacer de El Chaparro', 'Comuna Llano Oriental'],
    'Capital Miranda' => ['Comuna Pariaguán en Lucha', 'Comuna Faja del Orinoco'],
    'Atapirire' => ['Comuna Atapirire Productivo', 'Comuna Llano Adentro'],
    'Boca del Pao' => ['Comuna Orillas del Pao', 'Comuna Miranda Sur'],
    'El Pao' => ['Comuna El Pao de Barcelona', 'Comuna Tierra Fértil'],
    'Múcura' => ['Comuna Múcura Renace', 'Comuna Corazón de Miranda'],
    'Capital Monagas' => ['Comuna Mapire Progresa', 'Comuna Encuentro de Ríos'],
    'San Diego de Cabrutica' => ['Comuna Petrolera de San Diego', 'Comuna Orinoco Vive'],
    'Santa Clara' => ['Comuna Santa Clara del Orinoco', 'Comuna Monagas Productiva'],
    'Uverito' => ['Comuna Bosque de Uverito', 'Comuna Pinos del Caribe'],
    'Zuata' => ['Comuna Ganadera de Zuata', 'Comuna Ribera del Orinoco'],
    'Pariaguán' => ['Comuna Corazón de Pariaguán', 'Comuna El Progreso del Sur'],
    'Capital Peñalver' => ['Comuna Puerto Píritu Turístico', 'Comuna Viento de Peñalver'],
    'San Miguel' => ['Comuna San Miguel Arcángel', 'Comuna Costera del Sol'],
    'Capital Píritu' => ['Comuna Píritu Histórico', 'Comuna Tierra de Gracia'],
    'San Francisco' => ['Comuna San Francisco de Píritu', 'Comuna Sol de Oriente'],
    'Capital San Juan de Capistrano' => ['Comuna Boca de Uchire en Victoria', 'Comuna Laguna Viva'],
    'Boca de Chávez' => ['Comuna Pescadores de Boca de Chávez', 'Comuna El Hatillo Progresa'],
    'Capital Santa Ana' => ['Comuna Santa Ana de Anzoátegui', 'Comuna Corazón del Estado'],
    'Pueblo Nuevo' => ['Comuna Pueblo Nuevo Unido', 'Comuna El Renacer del Centro'],
    'El Tigre' => ['Comuna Petrolera El Tigre', 'Comuna Simón Rodríguez Avanza', 'Comuna Corazón de la Faja'],
    'Pozuelos' => ['Comuna Altos de Pozuelos', 'Comuna Puerto La Cruz Industrial'],
    'Capital Sotillo' => ['Comuna Puerto La Cruz Unida', 'Comuna Bahía de Pozuelos'],
    'Capital Bolívar' => ['Comuna Barcelona Unida', 'Comuna Corazón de Oriente'],
    'Simón Bolívar' => ['Comuna Barcelona en Batalla', 'Comuna El Viñedo de Barcelona'],

    // Apure
    'Capital Achaguas' => ['Comuna Llanera de Achaguas', 'Comuna Corazón del Llano'],
    'Apurito' => ['Comuna Apurito Renace', 'Comuna Sol de Apure'],
    'El Yagual' => ['Comuna El Yagual Productivo', 'Comuna Tierra de Héroes'],
    'Guachara' => ['Comuna Guachara Unida', 'Comuna Llano Adentro'],
    'Mucuritas' => ['Comuna Batalla de Mucuritas', 'Comuna Campo de Gloria'],
    'Queseras del Medio' => ['Comuna Queseras del Medio Heroica', 'Comuna Lanza de Páez'],
    'Capital Biruaca' => ['Comuna Biruaca en Progreso', 'Comuna Sol de Biruaca'],
    'Capital Muñoz' => ['Comuna Bruzual de Apure', 'Comuna Llano y Cielo'],
    'Mantecal' => ['Comuna Hato El Frío', 'Comuna Corazón de Mantecal'],
    'San Vicente' => ['Comuna San Vicente Ferrer', 'Comuna El Progreso del Llano'],
    'La Trinidad de Orichuna' => ['Comuna Orillas del Orichuna', 'Comuna Tierra de Palma'],
    'El Amparo' => ['Comuna Fronteriza El Amparo', 'Comuna Ribera del Arauca'],
    'Guasdualito' => ['Comuna Alto Apure en Lucha', 'Comuna Corazón de Guasdualito'],
    'Aramendi' => ['Comuna Aramendi Productiva', 'Comuna Viento Llanero'],
    'San Camilo' => ['Comuna El Nula Fronteriza', 'Comuna Selva de San Camilo'],
    'Urdaneta' => ['Comuna Urdaneta del Sur', 'Comuna Llano Alto'],
    'San Juan de Payara' => ['Comuna Cuna de la Revolución', 'Comuna Sol de Payara'],
    'Codazzi' => ['Comuna Puerto Páez Fluvial', 'Comuna Encuentro de Ríos'],
    'Cunaviche' => ['Comuna Cunaviche Adentro', 'Comuna Corazón de la Sabana'],
    'Elorza' => ['Comuna Alma Llanera de Elorza', 'Comuna Rómulo Gallegos Vive'],
    'La Trinidad' => ['Comuna La Trinidad de Apure', 'Comuna Progreso del Sur'],
    'Capital San Fernando' => ['Comuna San Fernando de Apure', 'Comuna Corazón de Venezuela'],
    'El Recreo' => ['Comuna El Recreo Unido', 'Comuna Sol del Capanaparo'],
    'Peñalver' => ['Comuna Peñalver del Llano', 'Comuna Tierra de Héroes'],
    'San Rafael de Atamaica' => ['Comuna Atamaica Productiva', 'Comuna Llano y Estero'],

    // Aragua
    'Capital Bolívar' => ['Comuna San Mateo Histórico', 'Comuna Ingenio Bolívar'],
    'Capital Camatagua' => ['Comuna Embalse de Camatagua', 'Comuna Corazón de Aragua'],
    'Carmen de Cura' => ['Comuna Valles de Carmen de Cura', 'Comuna Tierra de Fe'],
    'Santa Rita' => ['Comuna Santa Rita Progresa', 'Comuna Francisco Linares Alcántara'],
    'Francisco de Miranda' => ['Comuna Francisco de Miranda Unida', 'Comuna El Despertar del Sur'],
    'Monseñor Feliciano González' => ['Comuna Monseñor Feliciano', 'Comuna Fe y Esperanza'],
    'Pedro José Ovalles' => ['Comuna Pedro José Ovalles', 'Comuna Sur de Maracay'],
    'Joaquín Crespo' => ['Comuna Joaquín Crespo Vive', 'Comuna Corazón de Girardot'],
    'José Casanova Godoy' => ['Comuna Casanova Godoy Unida', 'Comuna El Progreso de Maracay'],
    'Madre María de San José' => ['Comuna Madre María', 'Comuna Beata de Aragua'],
    'Andrés Eloy Blanco' => ['Comuna Andrés Eloy Blanco', 'Comuna Poeta del Pueblo'],
    'Los Tacariguas' => ['Comuna Lago de los Tacariguas', 'Comuna Viento del Lago'],
    'Las Delicias' => ['Comuna Las Delicias Turística', 'Comuna Parque Nacional Henri Pittier'],
    'Choroní' => ['Comuna Cacao de Choroní', 'Comuna Costa de Aragua'],
    'Capital José Ángel Lamas' => ['Comuna Santa Cruz de Aragua', 'Comuna Corazón de Lamas'],
    'Capital José Félix Ribas' => ['Comuna La Victoria Heroica', 'Comuna Juventud de Ribas'],
    'Castor Nieves Ríos' => ['Comuna Castor Nieves Ríos', 'Comuna Montaña Adentro'],
    'Las Guacamayas' => ['Comuna Las Guacamayas Unida', 'Comuna Sol de Ribas'],
    'Pao de Zárate' => ['Comuna Pao de Zárate Productivo', 'Comuna Tierra Fértil'],
    'Zuata' => ['Comuna Zuata en Batalla', 'Comuna El Progreso del Este'],
    'Capital José Rafael Revenga' => ['Comuna El Consejo Progresa', 'Comuna Tierra de Revenga'],
    'Palo Negro' => ['Comuna Libertador de Aragua', 'Comuna Base Aérea Libertador'],
    'San Martín de Porres' => ['Comuna San Martín de Porres', 'Comuna Fe y Progreso'],
    'El Limón' => ['Comuna El Limón de Aragua', 'Comuna Río El Limón'],
    'Caña de Azúcar' => ['Comuna Caña de Azúcar en Lucha', 'Comuna Corazón de Mario Briceño'],
    'Capital Ocumare de la Costa de Oro' => ['Comuna Ocumare de la Costa', 'Comuna Cacao y Mar'],
    'Capital San Casimiro' => ['Comuna Valles de San Casimiro', 'Comuna Corazón del Sur de Aragua'],
    'Güiripa' => ['Comuna Güiripa Unida', 'Comuna Tierra de Progreso'],
    'Ollas de Caramacate' => ['Comuna Ollas de Caramacate', 'Comuna Montaña y Fe'],
    'Valle Morín' => ['Comuna Valles de Morín', 'Comuna El Renacer del Campo'],
    'Capital San Sebastián' => ['Comuna San Sebastián de los Reyes', 'Comuna Cuna de Reyes'],
    'Capital Santiago Mariño' => ['Comuna Turmero Unido', 'Comuna Corazón de Mariño'],
    'Arévalo Aponte' => ['Comuna Arévalo Aponte', 'Comuna El Mácaro Progresa'],
    'Chuao' => ['Comuna Cacao de Chuao', 'Comuna Costa de Oro'],
    'Samán de Güere' => ['Comuna Samán de Güere en Lucha', 'Comuna El Progreso de Mariño'],
    'Alfredo Pacheco Miranda' => ['Comuna Alfredo Pacheco Miranda', 'Comuna Sur de Turmero'],
    'Capital Santos Michelena' => ['Comuna Las Tejerías Industrial', 'Comuna Puerta de Aragua'],
    'Tiara' => ['Comuna Tiara Productiva', 'Comuna Montaña y Café'],
    'Capital Sucre' => ['Comuna Cagua Industrial', 'Comuna Corazón de Sucre'],
    'Bella Vista' => ['Comuna Bella Vista Unida', 'Comuna Lago de Valencia'],
    'Capital Tovar' => ['Comuna Colonia Tovar Turística', 'Comuna Rincón de Alemania'],
    'Capital Urdaneta' => ['Comuna Barbacoas Progresa', 'Comuna Sur de Aragua'],
    'San Francisco de Cara' => ['Comuna San Francisco de Cara', 'Comuna Tierra de Fe'],
    'Taguay' => ['Comuna Taguay Unido', 'Comuna Llano y Montaña'],
    'Capital Zamora' => ['Comuna Villa de Cura Heroica', 'Comuna Corazón de Zamora'],
    'Magdaleno' => ['Comuna Artesanos de Magdaleno', 'Comuna Lago y Progreso'],
    'San Francisco de Asís' => ['Comuna San Francisco de Asís', 'Comuna Tierra de Bendiciones'],
    'Valles de Tucutunemo' => ['Comuna Valles de Tucutunemo', 'Comuna Campo Fértil'],
    'Augusto Mijares' => ['Comuna Augusto Mijares', 'Comuna Zamora Unida'],

    // Barinas
    'Sabaneta' => ['Comuna Cuna de Chávez', 'Comuna Sol de Sabaneta'],
    'Rodríguez Domínguez' => ['Comuna Rodríguez Domínguez', 'Comuna Llano Alto'],
    'El Cantón' => ['Comuna El Cantón Fronterizo', 'Comuna Corazón del Llano Occidental'],
    'Santa Cruz de Guacas' => ['Comuna Santa Cruz de Guacas', 'Comuna Tierra de Progreso'],
    'Puerto Vivas' => ['Comuna Puerto Vivas Fluvial', 'Comuna Orillas del Uribante'],
    'Socopó' => ['Comuna Corazón de Socopó', 'Comuna Eje Andino-Llanero'],
    'Nicolás Pulido' => ['Comuna Nicolás Pulido', 'Comuna El Progreso del Sur'],
    'Andrés Bello' => ['Comuna Andrés Bello de Barinas', 'Comuna Llano y Montaña'],
    'Arismendi' => ['Comuna Arismendi de Barinas', 'Comuna Corazón del Llano'],
    'Guadarrama' => ['Comuna Guadarrama Unida', 'Comuna Tierra de Arroz'],
    'La Unión' => ['Comuna La Unión de Barinas', 'Comuna Llano Adentro'],
    'San Antonio' => ['Comuna San Antonio de Barinas', 'Comuna Progreso Llanero'],
    'Barinas' => ['Comuna Ciudad de Barinas', 'Comuna Corazón de la Patria'],
    'Alfredo Arvelo Larriva' => ['Comuna Alfredo Arvelo Larriva', 'Comuna El Poeta del Llano'],
    'San Silvestre' => ['Comuna San Silvestre Productivo', 'Comuna Tierra de Palma'],
    'Santa Inés' => ['Comuna Batalla de Santa Inés', 'Comuna Campo de Victoria'],
    'Santa Lucía' => ['Comuna Santa Lucía de Barinas', 'Comuna Fe y Esperanza'],
    'Torunos' => ['Comuna Torunos Unido', 'Comuna Llano Fértil'],
    'El Carmen' => ['Comuna El Carmen de Barinas', 'Comuna Centro Heroico'],
    'Rómulo Betancourt' => ['Comuna Rómulo Betancourt', 'Comuna El Progreso del Sur'],
    'Corazón de Jesús' => ['Comuna Corazón de Jesús', 'Comuna Barinas Unida'],
    'Ramón Ignacio Méndez' => ['Comuna Ramón Ignacio Méndez', 'Comuna El Educador del Llano'],
    'Alto Barinas' => ['Comuna Alto Barinas Progresa', 'Comuna Sol de la Ciudad'],
    'Manuel Palacio Fajardo' => ['Comuna Manuel Palacio Fajardo', 'Comuna Héroe de la Patria'],
    'Juan Antonio Rodríguez Domínguez' => ['Comuna Juan Antonio Rodríguez Domínguez', 'Comuna El Progreso del Oeste'],
    'Dominga Ortiz de Páez' => ['Comuna Dominga Ortiz de Páez', 'Comuna Mujer del Llano'],
    'Barinitas' => ['Comuna Pie de Monte Andino', 'Comuna Corazón de Barinitas'],
    'Altamira' => ['Comuna Altamira de Cáceres', 'Comuna Cuna del Café'],
    'Calderas' => ['Comuna Calderas Turística', 'Comuna Montaña y Neblina'],
    'Barrancas' => ['Comuna Barrancas de Barinas', 'Comuna Orillas del Masparro'],
    'El Socorro' => ['Comuna El Socorro Unido', 'Comuna Tierra de Progreso'],
    'Masparrito' => ['Comuna Masparrito Productivo', 'Comuna Llano Adentro'],
    'Santa Bárbara' => ['Comuna Santa Bárbara de Barinas', 'Comuna Corazón de Zamora'],
    'José Ignacio del Pumar' => ['Comuna José Ignacio del Pumar', 'Comuna El Marqués del Llano'],
    'Pedro Briceño Méndez' => ['Comuna Pedro Briceño Méndez', 'Comuna Héroe de Barinas'],
    'Obispos' => ['Comuna Obispos de Barinas', 'Comuna Tierra de Fe'],
    'El Real' => ['Comuna El Real de Barinas', 'Comuna Llano Fértil'],
    'La Luz' => ['Comuna La Luz del Llano', 'Comuna Esperanza y Progreso'],
    'Los Guasimitos' => ['Comuna Los Guasimitos', 'Comuna Campo Adentro'],
    'Ciudad Bolivia' => ['Comuna Corazón de Pedraza', 'Comuna Llano y Río'],
    'Ignacio Briceño' => ['Comuna Ignacio Briceño', 'Comuna El Progreso del Sur'],
    'José Félix Ribas' => ['Comuna José Félix Ribas de Pedraza', 'Comuna Héroe de la Juventud'],
    'Páez' => ['Comuna Páez de Pedraza', 'Comuna Lanza del Llano'],
    'Libertad' => ['Comuna Libertad de Rojas', 'Comuna Corazón del Llano Medio'],
    'Dolores' => ['Comuna Dolores de Rojas', 'Comuna Tierra de Fe y Tradición'],
    'Palacios Fajardo' => ['Comuna Palacios Fajardo', 'Comuna Héroe de la Independencia'],
    'Simón Rodríguez' => ['Comuna Simón Rodríguez de Rojas', 'Comuna El Maestro del Llano'],
    'Ciudad de Nutrias' => ['Comuna Ciudad de Nutrias', 'Comuna Corazón de Sosa'],
    'El Regalo' => ['Comuna El Regalo Productivo', 'Comuna Tierra de Bendiciones'],
    'Puerto de Nutrias' => ['Comuna Puerto de Nutrias Fluvial', 'Comuna Orillas del Apure'],
    'Santa Catalina' => ['Comuna Santa Catalina de Sosa', 'Comuna Fe y Progreso'],

    // Bolívar
    'Ciudad Piar' => ['Comuna Cerro Bolívar', 'Comuna Corazón de Hierro'],
    'San Francisco' => ['Comuna San Francisco de la Paragua', 'Comuna Tierra de Oro'],
    'San José' => ['Comuna San José de la Paragua', 'Comuna El Progreso Minero'],
    'Cachamay' => ['Comuna Parque Cachamay', 'Comuna Salto La Llovizna'],
    'Chirica' => ['Comuna Chirica en Lucha', 'Comuna San Félix Unido'],
    'Dalla Costa' => ['Comuna Dalla Costa Progresa', 'Comuna Corazón de Ciudad Guayana'],
    'Once de Abril' => ['Comuna 11 de Abril Heroica', 'Comuna El Despertar del Pueblo'],
    'Simón Bolívar' => ['Comuna Simón Bolívar de Caroní', 'Comuna Puerto Ordaz Industrial'],
    'Unare' => ['Comuna Unare en Victoria', 'Comuna Sol de Guayana'],
    'Universidad' => ['Comuna Universitaria de Guayana', 'Comuna El Saber es Poder'],
    'Vista al Sol' => ['Comuna Vista al Sol Renace', 'Comuna El Progreso del Este'],
    'Pozo Verde' => ['Comuna Pozo Verde Productivo', 'Comuna Tierra Fértil de Guayana'],
    'Yocoima' => ['Comuna Yocoima Unida', 'Comuna Reserva Forestal'],
    '5 de Julio' => ['Comuna 5 de Julio Patriota', 'Comuna El Grito de la Independencia'],
    'Caicara del Orinoco' => ['Comuna Caicara del Orinoco Fluvial', 'Comuna Corazón de Cedeño'],
    'Altagracia' => ['Comuna Altagracia de Cedeño', 'Comuna Tierra de Progreso'],
    'Ascensión Farreras' => ['Comuna Ascensión Farreras', 'Comuna Mujer Heroica'],
    'Guaniamo' => ['Comuna Diamantífera de Guaniamo', 'Comuna Selva Adentro'],
    'La Urbana' => ['Comuna La Urbana del Orinoco', 'Comuna Ribera del Río'],
    'Pijiguaos' => ['Comuna Bauxita de los Pijiguaos', 'Comuna El Orgullo Minero'],
    'Capital El Callao' => ['Comuna Aurífera de El Callao', 'Comuna Cuna del Calipso'],
    'Santa Elena de Uairén' => ['Comuna Puerta de la Gran Sabana', 'Comuna Tepuy Roraima'],
    'Ikabarú' => ['Comuna Ikabarú Ancestral', 'Comuna Tierra de Diamantes'],
    'Catedral' => ['Comuna Casco Histórico de Bolívar', 'Comuna Angostura Vive'],
    'Agua Salada' => ['Comuna Agua Salada en Lucha', 'Comuna El Progreso del Oeste'],
    'José Antonio Páez' => ['Comuna José Antonio Páez de Heres', 'Comuna Héroe de la Patria'],
    'La Sabanita' => ['Comuna La Sabanita Unida', 'Comuna Corazón del Sur'],
    'Marhuanta' => ['Comuna Marhuanta Progresa', 'Comuna Sol de la Ciudad'],
    'Vista Hermosa' => ['Comuna Vista Hermosa de Bolívar', 'Comuna El Mirador del Orinoco'],
    'Orinoco' => ['Comuna Orinoco Fluvial', 'Comuna Pescadores del Río Padre'],
    'Panapana' => ['Comuna Panapana Productiva', 'Comuna Tierra Fértil del Orinoco'],
    'Zea' => ['Comuna Zea de Heres', 'Comuna El Progreso del Este'],
    'Upata' => ['Comuna Villa del Yocoima', 'Comuna Corazón de Piar'],
    'Andrés Eloy Blanco' => ['Comuna Andrés Eloy Blanco de Piar', 'Comuna El Poeta de la Tierra'],
    'Pedro Cova' => ['Comuna El Manteco Minero', 'Comuna Tierra de Oro y Esperanza'],
    'Guasipati' => ['Comuna Guasipati en Victoria', 'Comuna Corazón de Roscio'],
    'Salom' => ['Comuna Salom Progresa', 'Comuna El Miamo Unido'],
    'Tumeremo' => ['Comuna Puerta del Esequibo', 'Comuna Corazón de Sifontes'],
    'San Isidro' => ['Comuna San Isidro Labrador de Sifontes', 'Comuna Kilómetro 88'],
    'Maripa' => ['Comuna Maripa Fluvial', 'Comuna Corazón de Sucre'],
    'Aripao' => ['Comuna Aripao Productivo', 'Comuna Tierra de Caura'],
    'Guarataro' => ['Comuna Guarataro Unido', 'Comuna Selva y Río'],
    'Las Majadas' => ['Comuna Las Majadas Progresa', 'Comuna Orillas del Caura'],
    'Moitaco' => ['Comuna Moitaco Ancestral', 'Comuna Ribera del Orinoco'],
    'El Palmar' => ['Comuna El Palmar en Lucha', 'Comuna Corazón de Padre Chien'],
    ];

        foreach ($communesByParish as $parishName => $communes) {
            $parish = Parish::where('name', $parishName)->first();

            if ($parish) {
                foreach ($communes as $commune) {
                    Commune::create([
                        'parish_id' => $parish->id,
                        'name' => $commune,
                    ]);
                }
            }
        }
    }
}
