<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Parish;
use App\Models\Municipality;

class ParishesTableSeeder extends Seeder
{
    public function run()
    {
        $parishesByMunicipality = [
            // Amazonas
            'Alto Orinoco' => ['Capital Alto Orinoco', 'Huachamacare', 'Marawaka', 'Mavaca', 'Sierra Parima'],
            'Atabapo' => ['Capital Atabapo', 'Ucata', 'Yapacana', 'Caname'],
            'Atures' => ['Fernando Girón Tovar', 'Luis Alberto Gómez', 'Pahueña', 'Platanillal'],
            'Autana' => ['Samariapo', 'Sipapo', 'Munduapo', 'Guayapo'],
            'Manapiare' => ['Capital Manapiare', 'Alto Ventuari', 'Medio Ventuari', 'Bajo Ventuari'],
            'Maroa' => ['Capital Maroa', 'Victorino'],
            'Río Negro' => ['Capital Río Negro', 'Casiquiare', 'Cocuy', 'San Carlos de Río Negro'],

            // Anzoátegui
            'Anaco' => ['Capital Anaco', 'San Joaquín', 'Buena Vista'],
            'Aragua' => ['Capital Aragua de Barcelona', 'Cachipo'],
            'Bolívar' => ['Bergantín', 'Caigua', 'El Carmen', 'El Pilar', 'Naricual', 'San Cristóbal'],
            'Bruzual' => ['Capital Bruzual', 'Guanape', 'Sabana de Uchire'],
            'Cajigal' => ['Capital Cajigal', 'San Pablo'],
            'Carvajal' => ['Capital Carvajal', 'Santa Bárbara'],
            'Diego Bautista Urbaneja' => ['Lechería', 'El Morro'],
            'Freites' => ['Capital Freites', 'Santa Rosa', 'Urica', 'Libertador', 'Huanipa'],
            'Guanipa' => ['Capital Guanipa'],
            'Guanta' => ['Capital Guanta', 'Chorrerón'],
            'Independencia' => ['Capital Independencia', 'Mamo'],
            'Libertad' => ['Capital Libertad', 'San Mateo'],
            'McGregor' => ['Capital McGregor', 'El Chaparro'],
            'Miranda' => ['Capital Miranda', 'Atapirire', 'Boca del Pao', 'El Pao', 'Múcura'],
            'Monagas' => ['Capital Monagas', 'San Diego de Cabrutica', 'Santa Clara', 'Uverito', 'Zuata', 'Pariaguán'],
            'Peñalver' => ['Capital Peñalver', 'San Miguel', 'Sucre'],
            'Píritu' => ['Capital Píritu', 'San Francisco'],
            'San Juan de Capistrano' => ['Capital San Juan de Capistrano', 'Boca de Chávez'],
            'Santa Ana' => ['Capital Santa Ana', 'Pueblo Nuevo'],
            'Simón Rodríguez' => ['El Tigre', 'Boca de Uchire'],
            'Sotillo' => ['Capital Sotillo', 'Pozuelos'],

            // Apure
            'Achaguas' => ['Capital Achaguas', 'Apurito', 'El Yagual', 'Guachara', 'Mucuritas', 'Queseras del Medio'],
            'Biruaca' => ['Capital Biruaca'],
            'Muñoz' => ['Capital Muñoz', 'Mantecal', 'San Vicente', 'La Trinidad de Orichuna', 'El Amparo'],
            'Páez' => ['Guasdualito', 'Aramendi', 'El Amparo', 'San Camilo', 'Urdaneta'],
            'Pedro Camejo' => ['San Juan de Payara', 'Codazzi', 'Cunaviche'],
            'Rómulo Gallegos' => ['Elorza', 'La Trinidad'],
            'San Fernando' => ['Capital San Fernando', 'El Recreo', 'Peñalver', 'San Rafael de Atamaica'],

            // Aragua
            'Bolívar' => ['Capital Bolívar'],
            'Camatagua' => ['Capital Camatagua', 'Carmen de Cura'],
            'Francisco Linares Alcántara' => ['Santa Rita', 'Francisco de Miranda', 'Monseñor Feliciano González'],
            'Girardot' => ['Pedro José Ovalles', 'Joaquín Crespo', 'José Casanova Godoy', 'Madre María de San José', 'Andrés Eloy Blanco', 'Los Tacariguas', 'Las Delicias', 'Choroní'],
            'José Ángel Lamas' => ['Capital José Ángel Lamas'],
            'José Félix Ribas' => ['Capital José Félix Ribas', 'Castor Nieves Ríos', 'Las Guacamayas', 'Pao de Zárate', 'Zuata'],
            'José Rafael Revenga' => ['Capital José Rafael Revenga'],
            'Libertador' => ['Palo Negro', 'San Martín de Porres'],
            'Mario Briceño Iragorry' => ['El Limón', 'Caña de Azúcar'],
            'Ocumare de la Costa de Oro' => ['Capital Ocumare de la Costa de Oro'],
            'San Casimiro' => ['Capital San Casimiro', 'Güiripa', 'Ollas de Caramacate', 'Valle Morín'],
            'San Sebastián' => ['Capital San Sebastián'],
            'Santiago Mariño' => ['Capital Santiago Mariño', 'Arévalo Aponte', 'Chuao', 'Samán de Güere', 'Alfredo Pacheco Miranda'],
            'Santos Michelena' => ['Capital Santos Michelena', 'Tiara'],
            'Sucre' => ['Capital Sucre', 'Bella Vista'],
            'Tovar' => ['Capital Tovar'],
            'Urdaneta' => ['Capital Urdaneta', 'San Francisco de Cara', 'Taguay'],
            'Zamora' => ['Capital Zamora', 'Magdaleno', 'San Francisco de Asís', 'Valles de Tucutunemo', 'Augusto Mijares'],

            // Barinas
            'Alberto Arvelo Torrealba' => ['Sabaneta', 'Rodríguez Domínguez'],
            'Andrés Eloy Blanco' => ['El Cantón', 'Santa Cruz de Guacas', 'Puerto Vivas'],
            'Antonio José de Sucre' => ['Socopó', 'Nicolás Pulido', 'Andrés Bello'],
            'Arismendi' => ['Arismendi', 'Guadarrama', 'La Unión', 'San Antonio'],
            'Barinas' => ['Barinas', 'Alfredo Arvelo Larriva', 'San Silvestre', 'Santa Inés', 'Santa Lucía', 'Torunos', 'El Carmen', 'Rómulo Betancourt', 'Corazón de Jesús', 'Ramón Ignacio Méndez', 'Alto Barinas', 'Manuel Palacio Fajardo', 'Juan Antonio Rodríguez Domínguez', 'Dominga Ortiz de Páez'],
            'Bolívar' => ['Barinitas', 'Altamira', 'Calderas'],
            'Cruz Paredes' => ['Barrancas', 'El Socorro', 'Masparrito'],
            'Ezequiel Zamora' => ['Santa Bárbara', 'José Ignacio del Pumar', 'Pedro Briceño Méndez', 'Ramón Ignacio Méndez'],
            'Obispos' => ['Obispos', 'El Real', 'La Luz', 'Los Guasimitos'],
            'Pedraza' => ['Ciudad Bolivia', 'Ignacio Briceño', 'José Félix Ribas', 'Páez'],
            'Rojas' => ['Libertad', 'Dolores', 'Palacios Fajardo', 'Simón Rodríguez'],
            'Sosa' => ['Ciudad de Nutrias', 'El Regalo', 'Puerto de Nutrias', 'Santa Catalina'],

            // Bolívar
            'Angostura' => ['Ciudad Piar', 'San Francisco', 'San José'],
            'Caroní' => ['Cachamay', 'Chirica', 'Dalla Costa', 'Once de Abril', 'Simón Bolívar', 'Unare', 'Universidad', 'Vista al Sol', 'Pozo Verde', 'Yocoima', '5 de Julio'],
            'Cedeño' => ['Caicara del Orinoco', 'Altagracia', 'Ascensión Farreras', 'Guaniamo', 'La Urbana', 'Pijiguaos'],
            'El Callao' => ['Capital El Callao'],
            'Gran Sabana' => ['Santa Elena de Uairén', 'Ikabarú'],
            'Heres' => ['Catedral', 'Agua Salada', 'José Antonio Páez', 'La Sabanita', 'Marhuanta', 'Vista Hermosa', 'Orinoco', 'Panapana', 'Zea'],
            'Piar' => ['Upata', 'Andrés Eloy Blanco', 'Pedro Cova'],
            'Roscio' => ['Guasipati', 'Salom'],
            'Sifontes' => ['Tumeremo', 'Dalla Costa', 'San Isidro'],
            'Sucre' => ['Maripa', 'Aripao', 'Guarataro', 'Las Majadas', 'Moitaco'],
            'Padre Pedro Chien' => ['El Palmar'],
            
            // Carabobo
            'Bejuma' => ['Bejuma', 'Canoabo', 'Simón Bolívar'],
            'Carlos Arvelo' => ['Güigüe', 'Belén', 'Tacarigua'],
            'Diego Ibarra' => ['Mariara', 'Aguas Calientes'],
            'Guacara' => ['Guacara', 'Yagua', 'Ciudad Alianza'],
            'Juan José Mora' => ['Morón', 'Urama'],
            'Libertador' => ['Tocuyito', 'Independencia'],
            'Los Guayos' => ['Capital Los Guayos'],
            'Miranda' => ['Miranda'],
            'Montalbán' => ['Montalbán'],
            'Naguanagua' => ['Capital Naguanagua'],
            'Puerto Cabello' => ['Bartolomé Salom', 'Democracia', 'Fraternidad', 'Goaigoaza', 'Juan José Flores', 'Unión', 'Borburata', 'Patanemo'],
            'San Diego' => ['Capital San Diego'],
            'San Joaquín' => ['Capital San Joaquín'],
            'Valencia' => ['Candelaria', 'Catedral', 'El Socorro', 'Miguel Peña', 'Rafael Urdaneta', 'San Blas', 'San José', 'Santa Rosa', 'Negro Primero'],

            // Cojedes
            'Anzoátegui' => ['Cojedes', 'Juan de Mata Suárez'],
            'Falcón' => ['Tinaquillo'],
            'Girardot' => ['El Baúl', 'Sucre'],
            'Lima Blanco' => ['Macapo'],
            'Pao de San Juan Bautista' => ['El Pao'],
            'Ricaurte' => ['Libertad', 'El Amparo'],
            'Rómulo Gallegos' => ['Las Vegas'],
            'San Carlos' => ['San Carlos de Austria', 'Juan Ángel Bravo', 'Manuel Manrique'],
            'Tinaco' => ['General en Jefe José Laurencio Silva'],

            // Delta Amacuro
            'Antonio Díaz' => ['Curiapo', 'Almirante Luis Brión', 'Francisco Aniceto Lugo', 'Manuel Renaud', 'Padre Barral', 'Santos de Abelgas'],
            'Casacoima' => ['Sierra Imataca', 'Juan Bautista Arismendi', 'Manuel Piar', 'Rómulo Gallegos'],
            'Pedernales' => ['Pedernales', 'Luis Beltrán Prieto Figueroa'],
            'Tucupita' => ['San José', 'José Vidal Marcano', 'Juan Millán', 'Leonardo Ruiz Pineda', 'Mariscal Antonio José de Sucre', 'Monseñor Argimiro García', 'San Rafael', 'Virgen del Valle'],

            // Distrito Capital
            'Libertador' => ['Altagracia', 'Antímano', 'Candelaria', 'Caricuao', 'Catedral', 'Coche', 'El Junquito', 'El Paraíso', 'El Recreo', 'El Valle', 'La Pastora', 'La Vega', 'Macarao', 'San Agustín', 'San Bernardino', 'San José', 'San Juan', 'San Pedro', 'Santa Rosalía', 'Santa Teresa', 'Sucre', '23 de Enero'],

            // Falcón
            'Acosta' => ['San Juan de los Cayos', 'Capadare', 'La Pastora', 'Libertador', 'San Gabriel'],
            'Bolívar' => ['San Luis', 'Aracua', 'La Peña'],
            'Buchivacoa' => ['Capatárida', 'Bariro', 'Borojó', 'Guajiro', 'Seque', 'Zazárida'],
            'Cacique Manaure' => ['Yaracal', 'Cacique Manaure'],
            'Carirubana' => ['Carirubana', 'Norte', 'Punta Cardón', 'Santa Ana'],
            'Colina' => ['La Vela de Coro', 'Acurigua', 'Guaibacoa', 'Las Calderas', 'Macoruca'],
            'Dabajuro' => ['Dabajuro'],
            'Democracia' => ['Pedregal', 'Agua Clara', 'Avaria', 'Piedra Grande', 'Purureche'],
            'Falcón' => ['Pueblo Nuevo', 'Adícora', 'Baraived', 'Buena Vista', 'Jadacaquiva', 'Moruy', 'Adaure', 'El Vínculo', 'El Hato'],
            'Federación' => ['Churuguara', 'Agua Larga', 'El Paují', 'Independencia', 'Mapararí'],
            'Jacura' => ['Jacura', 'Agua Linda', 'El Araurima'],
            'Los Taques' => ['Santa Cruz de Bucaral', 'El Charal', 'Las Vegas del Tuy'],
            'Mauroa' => ['Mene de Mauroa', 'San Félix', 'Casigua'],
            'Miranda' => ['San Antonio de Padua de la Concordia de Coro', 'Guzmán Guillermo', 'Mitare', 'Río Seco', 'Sabaneta'],
            'Monseñor Iturriza' => ['Chichiriviche', 'Boca de Tocuyo', 'Tocuyo de la Costa'],
            'Palmasola' => ['Palmasola'],
            'Petit' => ['Cabure', 'Colina', 'Curimagua'],
            'Píritu' => ['Píritu', 'San José de la Costa'],
            'San Francisco' => ['Mirimire', 'Capital San Francisco'],
            'Silva' => ['Tucacas', 'Boca de Aroa'],
            'Sucre' => ['La Cruz de Taratara', 'Sucre'],
            'Tocópero' => ['Tocópero'],
            'Unión' => ['Santa Cruz de Bucaral', 'El Charal', 'Las Vegas del Tuy'],
            'Urumaco' => ['Urumaco', 'Bruzual'],
            'Zamora' => ['Puerto Cumarebo', 'La Ciénaga', 'La Soledad', 'Pueblo Cumarebo', 'Zazárida'],

            // Guárico
            'Camaguán' => ['Camaguán', 'Puerto Miranda', 'Uverito'],
            'Chaguaramas' => ['Chaguaramas'],
            'El Socorro' => ['El Socorro'],
            'Francisco de Miranda' => ['Calabozo', 'El Calvario', 'El Rastro', 'Guardatinajas'],
            'José Félix Ribas' => ['Tucupido', 'San Rafael de Laya', 'San Francisco Javier de Laya'],
            'José Tadeo Monagas' => ['Altagracia de Orituco', 'San Rafael de Orituco', 'San Francisco Javier de Lezama', 'Paso Real de Macaira', 'Carlos Soublette', 'San Francisco de Macaira', 'Libertad de Orituco'],
            'Juan Germán Roscio' => ['San Juan de los Morros', 'Cantagallo', 'Parapara'],
            'Julián Mellado' => ['El Sombrero', 'Sosa'],
            'Las Mercedes' => ['Las Mercedes', 'Cabruta', 'Santa Rita de Manapire'],
            'Leonardo Infante' => ['Valle de la Pascua', 'Espino'],
            'Ortiz' => ['Ortiz', 'San José de Tiznados', 'San Francisco de Tiznados', 'San Lorenzo de Tiznados'],
            'Pedro Zaraza' => ['Zaraza', 'San José de Unare'],
            'San Gerónimo de Guayabal' => ['Guayabal', 'Cazorla'],
            'San José de Guaribe' => ['San José de Guaribe'],
            'Santa María de Ipire' => ['Santa María de Ipire', 'Altamira'],

            // La Guaira
            'Vargas' => ['Caraballeda', 'Carayaca', 'Catia La Mar', 'El Junko', 'La Guaira', 'Macuto', 'Maiquetía', 'Naiguatá', 'Urimare', 'Carlos Soublette', 'Raúl Leoni'],

            // Lara
            'Andrés Eloy Blanco' => ['Sanare', 'Pío Tamayo', 'Quebrada Honda de Guache', 'Yacambú'],
            'Crespo' => ['Duaca', 'Freitez', 'José María Blanco'],
            'Iribarren' => ['Catedral', 'Concepción', 'El Cují', 'Juan de Villegas', 'Santa Rosa', 'Tamaca', 'Unión', 'Aguedo Felipe Alvarado', 'Buena Vista', 'Juárez'],
            'Jiménez' => ['Quíbor', 'Diego de Lozada', 'Paraíso de San José', 'San Miguel', 'Tintorero', 'José Bernardo Dorante', 'Coronel Mariano Peraza', 'Cuara'],
            'Morán' => ['El Tocuyo', 'Anzoátegui', 'Bolívar', 'Guarico', 'Hilario Luna y Luna', 'Humocaro Alto', 'Humocaro Bajo', 'La Candelaria', 'Morán'],
            'Palavecino' => ['Cabudare', 'José Gregorio Bastidas', 'Agua Viva'],
            'Simón Planas' => ['Sarare', 'Buría', 'Gustavo Vegas León'],
            'Torres' => ['Carora', 'Trinidad Samuel', 'Antonio Díaz', 'Camacaro', 'Castañeda', 'Cecilio Zubillaga', 'Chiquinquirá', 'El Blanco', 'Espinoza de los Monteros', 'Heriberto Arroyo', 'Lara', 'Las Mercedes', 'Manuel Morillo', 'Montaña Verde', 'Montes de Oca', 'Reyes Vargas', 'Torres'],
            'Urdaneta' => ['Siquisique', 'Moroturo', 'San Miguel', 'Xaguas'],

            // Mérida
            'Alberto Adriani' => ['Presidente Betancourt', 'Presidente Páez', 'Presidente Rómulo Gallegos', 'Gabriel Picón González', 'Héctor Amable Mora', 'José Nucete Sardi', 'Pulido Méndez'],
            'Andrés Bello' => ['La Azulita'],
            'Antonio Pinto Salinas' => ['Santa Cruz de Mora', 'Mesa Bolívar', 'Mesa de Las Palmas'],
            'Aricagua' => ['Aricagua', 'San Antonio'],
            'Arzobispo Chacón' => ['Canaguá', 'Capurí', 'Chacantá', 'El Molino', 'Guaimaral', 'Mucutuy', 'Mucuchachí'],
            'Campo Elías' => ['Fernández Peña', 'Jají', 'La Mesa', 'Matriz', 'Montalbán'],
            'Caracciolo Parra Olmedo' => ['Tucaní', 'Florencio Ramírez'],
            'Cardenal Quintero' => ['Santo Domingo', 'Las Piedras'],
            'Guaraque' => ['Guaraque', 'Mesa de Quintero', 'Río Negro'],
            'Julio César Salas' => ['Arapuey', 'Palmira'],
            'Justo Briceño' => ['Torondoy', 'San Cristóbal de Torondoy'],
            'Libertador' => ['Antonio Spinetti Dini', 'Arias', 'Caracciolo Parra Pérez', 'Domingo Peña', 'El Llano', 'Gonzalo Picón Febres', 'Jacinto Plaza', 'Juan Rodríguez Suárez', 'Lasso de la Vega', 'Mariano Picón Salas', 'Milla', 'Osuna Rodríguez', 'Sagrario', 'El Morro', 'Los Nevados'],
            'Miranda' => ['Timotes', 'Andrés Eloy Blanco', 'La Venta', 'Piñango'],
            'Obispo Ramos de Lora' => ['Santa Elena de Arenales', 'Eloy Paredes', 'San Rafael de Alcázar'],
            'Padre Noguera' => ['Santa María de Caparo'],
            'Pueblo Llano' => ['Pueblo Llano'],
            'Rangel' => ['Mucurubá', 'Cacute', 'La Toma', 'Mucuchíes', 'San Rafael'],
            'Rivas Dávila' => ['Bailadores', 'Gerónimo Maldonado'],
            'Santos Marquina' => ['Tabay'],
            'Sucre' => ['Lagunillas', 'Chiguará', 'Estánques', 'La Trampa', 'Pueblo Nuevo del Sur', 'San Juan'],
            'Tovar' => ['Tovar', 'El Amparo', 'El Llano', 'San Francisco', 'Gerónimo Maldonado'],
            'Tulio Febres Cordero' => ['Nueva Bolivia', 'Independencia', 'María de la Concepción Palacios Blanco', 'Santa Apolonia'],
            'Zea' => ['Zea', 'Caño El Tigre'],

            // Miranda
            'Acevedo' => ['Caucagua', 'Aragüita', 'Arévalo González', 'Capaya', 'El Café', 'Marizapa', 'Panaquire', 'Ribas'],
            'Andrés Bello' => ['San José de Barlovento'],
            'Baruta' => ['Nuestra Señora del Rosario de Baruta', 'El Cafetal', 'Las Minas de Baruta'],
            'Brión' => ['Higuerote', 'Curiepe', 'Tacarigua'],
            'Buroz' => ['Mamporal'],
            'Carrizal' => ['Carrizal'],
            'Chacao' => ['Capital Chacao'],
            'Cristóbal Rojas' => ['Charallave', 'Las Brisas'],
            'El Hatillo' => ['Capital El Hatillo'],
            'Guaicaipuro' => ['Los Teques', 'Altagracia de la Montaña', 'Cecilio Acosta', 'El Jarillo', 'Paracotos', 'San Pedro', 'Tácata'],
            'Independencia' => ['Santa Teresa del Tuy', 'Cartanal'],
            'Lander' => ['Ocumare del Tuy', 'La Democracia', 'Santa Bárbara'],
            'Los Salias' => ['San Antonio de los Altos'],
            'Páez' => ['Río Chico', 'El Guapo', 'Higuerote', 'Tacarigua de la Laguna', 'Paparo'],
            'Paz Castillo' => ['Santa Lucía'],
            'Pedro Gual' => ['Cúpira', 'Machurucuto'],
            'Plaza' => ['Guarenas'],
            'Salón' => ['Guatire', 'Bolívar'],
            'Simón Bolívar' => ['San Francisco de Yare', 'San Antonio de Yare'],
            'Sucre' => ['Petare', 'Caucagüita', 'Filas de Mariche', 'La Dolorita', 'Leoncio Martínez'],
            'Urdaneta' => ['Cúa', 'Nueva Cúa'],
            'Zamora' => ['Guatire', 'Bolívar'],

            // Monagas
            'Acosta' => ['San Antonio de Capayacuar', 'Caripe del Guácharo'],
            'Bolívar' => ['Caripito', 'Caripito'],
            'Caripe' => ['Caripe', 'El Guácharo', 'La Guanota', 'Sabana de Piedra', 'San Agustín', 'Teresén'],
            'Cedeño' => ['Caicara', 'Areo', 'San Félix', 'Viento Fresco'],
            'Ezequiel Zamora' => ['Punta de Mata', 'El Tejero'],
            'Libertador' => ['Temblador', 'Las Alhuacas', 'Tabasca', 'Chaguaramas'],
            'Maturín' => ['Alto de los Godos', 'Boquerón', 'Las Cocuizas', 'La Pica', 'San Simón', 'Santa Cruz', 'El Corozo', 'El Furrial', 'Jusepín', 'San Vicente'],
            'Piar' => ['Aragua de Maturín', 'Aparicio', 'Chaguaramal', 'El Pinto', 'Guanaguana', 'La Toscana', 'Taguaya'],
            'Punceres' => ['Quiriquire', 'Cachipo'],
            'Santa Bárbara' => ['Santa Bárbara', 'Morón'],
            'Sotillo' => ['Barrancas', 'Los Barrancos de Fajardo'],
            'Uracoa' => ['Uracoa'],

            // Nueva Esparta
            'Antolín del Campo' => ['La Plaza de Paraguachí'],
            'Arismendi' => ['La Asunción'],
            'Díaz' => ['Parroquia San Juan Bautista', 'Zabala'],
            'García' => ['El Valle del Espíritu Santo'],
            'Gómez' => ['Santa Ana', 'Bolívar', 'Guevara', 'Matasiete', 'Sucre'],
            'Maneiro' => ['Pampatar', 'Aguirre'],
            'Marcano' => ['Juan Griego', 'Adrián'],
            'Mariño' => ['Porlamar'],
            'Península de Macanao' => ['Boca de Río', 'San Francisco'],
            'Tubores' => ['Punta de Piedras', 'Los Barales'],
            'Villalba' => ['San Pedro de Coche', 'Vicente Fuentes'],

            // Portuguesa
            'Agua Blanca' => ['Agua Blanca'],
            'Araure' => ['Araure', 'Río Acarigua'],
            'Esteller' => ['Píritu', 'Uveral'],
            'Guanare' => ['Guanare', 'Córdoba', 'San José de la Montaña', 'San Juan de Guanaguanare', 'Virgen de la Coromoto'],
            'Guanarito' => ['Guanarito', 'Trinidad de la Capilla', 'Divina Pastora'],
            'Monseñor José Vicente de Unda' => ['Paraíso de Chabasquén', 'Peña Blanca'],
            'Ospino' => ['Ospino', 'Aparición', 'La Estación'],
            'Páez' => ['Acarigua', 'Payara', 'Pimpinela', 'Ramón Peraza'],
            'Papelón' => ['Papelón', 'Caño Delgadito'],
            'San Genaro de Boconoíto' => ['Boconoíto', 'Antolín Tovar'],
            'San Rafael de Onoto' => ['San Rafael de Onoto', 'Santa Fe', 'Thermo Morles'],
            'Santa Rosalía' => ['El Playón', 'Florida'],
            'Sucre' => ['Biscucuy', 'Concepción', 'San José de Saguaz', 'San Rafael de Palo Alzao', 'Uvencio Antonio Velásquez'],
            'Turén' => ['Villa Bruzual', 'Canelones', 'Santa Cruz', 'San Isidro Labrador'],

            // Sucre
            'Andrés Eloy Blanco' => ['Casanay', 'Mariño', 'Rómulo Gallegos'],
            'Andrés Mata' => ['San José de Aerocuar', 'Tavera Acosta'],
            'Arismendi' => ['Río Caribe', 'Antonio José de Sucre', 'El Morro de Puerto Santo', 'Puerto Santo', 'San Juan de las Galdonas'],
            'Benítez' => ['El Pilar', 'El Rincón', 'General Francisco Antonio Vásquez', 'Guaraúnos', 'Tunapuicito', 'Unión'],
            'Bermúdez' => ['Carúpano', 'Santa Catalina', 'Santa Rosa', 'Santa Teresa', 'Bolívar', 'Macarapana'],
            'Bolívar' => ['Marigüitar'],
            'Cajigal' => ['Yaguaraparo', 'El Paujil', 'Libertad'],
            'Cruz Salmerón Acosta' => ['Araya', 'Chacopata', 'Manicuare'],
            'Libertador' => ['Tunapuy', 'Campo Elías'],
            'Mariño' => ['Irapa', 'Campo Claro', 'Marabal', 'San Antonio de Irapa', 'Soro'],
            'Mejía' => ['San Antonio del Golfo'],
            'Montes' => ['Cumanacoa', 'Arenas', 'Aricagua', 'Cocollar', 'San Fernando', 'San Lorenzo'],
            'Ribero' => ['Cariaco', 'Catuaro', 'Rendón', 'Santa Cruz', 'Santa María'],
            'Sucre' => ['Altagracia', 'Ayacucho', 'San Juan', 'Valentín Valiente', 'Santa Inés', 'Raúl Leoni', 'Gran Mariscal'],
            'Valdez' => ['Güiria', 'Bideau', 'Cristóbal Colón', 'Punta de Piedras'],
            
            // Táchira
            'Andrés Bello' => ['Cordero'],
            'Antonio Rómulo Costa' => ['Las Mesas'],
            'Ayacucho' => ['Colón', 'Rivas Berti', 'San Pedro del Río'],
            'Bolívar' => ['San Antonio del Táchira', 'El Palotal', 'Juan Vicente Gómez', 'Isaías Medina Angarita'],
            'Cárdenas' => ['Táriba', 'Amenodoro Rangel Lamus', 'La Florida'],
            'Córdoba' => ['Santa Ana del Táchira'],
            'Fernández Feo' => ['San Rafael del Piñal', 'Alberto Adriani', 'Santo Domingo'],
            'Francisco de Miranda' => ['San José de Bolívar'],
            'García de Hevia' => ['La Fría', 'Boca de Grita', 'José Antonio Páez'],
            'Guásimos' => ['Palmira'],
            'Independencia' => ['Capacho Nuevo', 'Juan Germán Roscio', 'Román Cárdenas'],
            'Jáuregui' => ['La Grita', 'Emilio Constantino Guerrero', 'Monseñor Miguel Antonio Salas'],
            'José María Vargas' => ['El Cobre'],
            'Junín' => ['Rubio', 'Bramón', 'La Petrólea', 'Quinimarí'],
            'Libertad' => ['Capacho Viejo', 'Cipriano Castro', 'Manuel Felipe Rugeles'],
            'Libertador' => ['Abejales', 'Doradas', 'Emeterio Ochoa', 'San Joaquín de Navay'],
            'Lobatera' => ['Lobatera', 'Constitución'],
            'Michelena' => ['Michelena'],
            'Panamericano' => ['Coloncito', 'La Palmita'],
            'Pedro María Ureña' => ['Ureña', 'Nueva Arcadia'],
            'Rafael Urdaneta' => ['Delicias'],
            'Samuel Darío Maldonado' => ['La Tendida', 'Boconó', 'Hernández'],
            'San Cristóbal' => ['La Concordia', 'Pedro María Morantes', 'San Juan Bautista', 'San Sebastián', 'Dr. Francisco Romero Lobo'],
            'San Judas Tadeo' => ['Umuquena'],
            'Seboruco' => ['Seboruco'],
            'Simón Rodríguez' => ['San Simón'],
            'Sucre' => ['Queniquea', 'Eleazar López Contreras', 'San Pablo'],
            'Torbes' => ['San Josecito', 'Las Vegas de Táriba', 'Michelena'],
            'Uribante' => ['Pregonero', 'Cárdenas', 'Juan Pablo Peñaloza', 'Potosí'],

            // Trujillo
            'Andrés Bello' => ['Santa Isabel', 'Araguaney', 'El Jaguito', 'La Esperanza'],
            'Boconó' => ['Boconó', 'El Carmen', 'Mosquey', 'Ayacucho', 'Burbusay', 'General Ribas', 'Guaramacal', 'La Vega de Guaramacal', 'Monseñor Jáuregui', 'Rafael Rangel', 'San José', 'San Miguel'],
            'Bolívar' => ['Sabana Grande', 'Cheregüé', 'Granados'],
            'Candelaria' => ['Chejendé', 'Arnoldo Gabaldón', 'Bolivia', 'Carrillo', 'Cegarra', 'Manuel Salvador Ulloa', 'San José'],
            'Carache' => ['Carache', 'La Concepción', 'Cuicas', 'Panamericana', 'Santa Cruz'],
            'Escuque' => ['Escuque', 'La Unión', 'Sabana Libre', 'Santa Rita'],
            'José Felipe Márquez Cañizales' => ['El Paradero', 'Antonio José de Sucre', 'El Socorro'],
            'Juan Vicente Campo Elías' => ['Campo Elías', 'Arnoldo Gabaldón'],
            'La Ceiba' => ['Santa Apolonia', 'El Progreso', 'La Ceiba', 'Tres de Febrero'],
            'Miranda' => ['El Dividive', 'Agua Santa', 'Agua Caliente', 'El Cenizo'],
            'Monte Carmelo' => ['Monte Carmelo', 'Buena Vista', 'Santa María del Horcón'],
            'Motatán' => ['Motatán', 'El Baño', 'Jalisco'],
            'Pampán' => ['Pampán', 'Flor de Patria', 'La Paz', 'Santa Ana'],
            'Pampanito' => ['Pampanito', 'La Concepción', 'Pampanito II'],
            'Rafael Rangel' => ['Betijoque', 'José Gregorio Hernández', 'La Pueblita', 'Los Cedros'],
            'San Rafael de Carvajal' => ['Carvajal', 'Antonio Nicolás Briceño', 'Campo Alegre', 'José Leonardo Suárez'],
            'Sucre' => ['Sabana de Mendoza', 'Junín', 'Valmore Rodríguez', 'El Paraíso'],
            'Trujillo' => ['Cristóbal Mendoza', 'Chiquinquirá', 'Andrés Linares', 'Cruz Carrillo', 'Matriz', 'Monseñor Carrillo', 'Tres Esquinas'],
            'Urdaneta' => ['La Quebrada', 'Cabimbú', 'Jajó', 'La Mesa de Esnujaque', 'Santiago', 'Tuñame'],
            'Valera' => ['Juan Ignacio Montilla', 'La Beatriz', 'La Puerta', 'Mendoza del Valle de Momboy', 'Mercedes Díaz', 'San Luis'],

            // Yaracuy
            'Arístides Bastidas' => ['San Pablo'],
            'Bolívar' => ['Aroa'],
            'Bruzual' => ['Chivacoa', 'Campo Elías'],
            'Cocorote' => ['Cocorote'],
            'Independencia' => ['Independencia'],
            'José Antonio Páez' => ['Sabana de Parra', 'José Antonio Páez'],
            'La Trinidad' => ['Boraure'],
            'Manuel Monge' => ['Yumare'],
            'Nirgua' => ['Nirgua', 'Salom', 'Temerla'],
            'Peña' => ['Yaritagua', 'San Andrés'],
            'San Felipe' => ['San Felipe', 'Albarico', 'Marín'],
            'Sucre' => ['Guama'],
            'Urachiche' => ['Urachiche'],
            'Veroes' => ['Farriar', 'El Guayabo'],

            // Zulia
            'Almirante Padilla' => ['El Toro', 'Isla de Toas', 'Monagas'],
            'Baralt' => ['San Timoteo', 'General Urdaneta', 'Libertador', 'Manuel Guanipa Matos', 'Marcelino Briceño', 'Pueblo Nuevo'],
            'Cabimas' => ['Ambrosio', 'Carmen Herrera', 'La Rosa', 'San Benito', 'Arístides Calvani', 'Jorge Hernández', 'Rómulo Betancourt', 'Punta Gorda', 'Germán Ríos Linares'],
            'Catatumbo' => ['Encontrados', 'Santa Bárbara'],
            'Colón' => ['San Carlos del Zulia', 'Moralito', 'San Rafael', 'Santa Bárbara', 'Urribarrí'],
            'Francisco Javier Pulgar' => ['Pueblo Nuevo-El Chivo', 'Agustín Codazzi', 'Carlos Quevedo', 'Francisco Javier Pulgar'],
            'Guajira' => ['Sinamaica', 'Alta Guajira', 'Elías Sánchez Rubio', 'Guajira'],
            'Jesús Enrique Lossada' => ['La Concepción', 'San José', 'Mariano Parra León', 'José Ramón Yépez'],
            'Jesús María Semprún' => ['Casigua el Cubo', 'Barí'],
            'La Cañada de Urdaneta' => ['Concepción', 'Andrés Bello', 'Chiquinquirá', 'El Carmelo', 'Potreritos'],
            'Lagunillas' => ['Libertad', 'Alonso de Ojeda', 'Campo Lara', 'Eleazar López Contreras', 'Venezuela', 'Blanca de Pérez'],
            'Machiques de Perijá' => ['Libertad', 'Bartolomé de las Casas', 'San José de Perijá', 'Río Negro'],
            'Mara' => ['San Rafael de El Moján', 'Ricauter', 'Tamare', 'Luis de Vicente'],
            'Maracaibo' => ['Antonio Borjas Romero', 'Bolívar', 'Cacique Mara', 'Caracciolo Parra Pérez', 'Cecilio Acosta', 'Cristo de Aranza', 'Coquivacoa', 'Chiquinquirá', 'Francisco Eugenio Bustamante', 'Idelfonso Vásquez', 'Juana de Ávila', 'Luis Hurtado Higuera', 'Manuel Dagnino', 'Olegario Villalobos', 'Raúl Leoni', 'Santa Lucía', 'Venancio Pulgar', 'San Isidro'],
            'Miranda' => ['Altagracia', 'Ana María Campos', 'Faría', 'San Antonio', 'San José'],
            'Rosario de Perijá' => ['El Rosario', 'Donaldo García', 'Sixto Zambrano'],
            'San Francisco' => ['San Francisco', 'El Bajo', 'Domitila Flores', 'Francisco Ochoa', 'José Domingo Rus', 'Marcial Hernández'],
            'Santa Rita' => ['Santa Rita', 'El Mene', 'Pedro Lucas Urribarrí', 'José Cenobio Urribarrí'],
            'Simón Bolívar' => ['Tía Juana', 'Manuel Manrique', 'Rafael María Baralt'],
            'Sucre' => ['Bobures', 'Gibraltar', 'Heras', 'Monseñor Arturo Celestino Álvarez', 'Rómulo Gallegos'],
            'Valmore Rodríguez' => ['La Victoria', 'Rafael Urdaneta', 'Raúl Cuenca'],
        ];

        foreach ($parishesByMunicipality as $municipalityName => $parishes) {
            $municipality = Municipality::where('name', $municipalityName)->first();

            if ($municipality) {
                foreach ($parishes as $parish) {
                    Parish::create([
                        'municipality_id' => $municipality->id,
                        'name' => $parish,
                    ]);
                }
            }
        }
    }
}
