services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # MYSQL_ROOT_HOST: localhost
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_USER: root
      # MYSQL_USER: laravel
      # MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  mysql_data: